parameters:
  telegram:
    name:
    username:
    api:
      url:
      token:
      proxy:

services:
  get_set_method_normalizer:

  TelegramBundle\Interfaces\SendMessageInterface:
      class: TelegramBundle\SendMessageService
      public: true
      arguments:
        - '@service_container'
        - '@event_dispatcher'
        - '@serializer'

  TelegramBundle\Controller\ClientController:
      class: TelegramBundle\Controller\ClientController
      public: true
      arguments:
        - '@TelegramBundle\Interfaces\SendMessageInterface'
        - '@monolog.logger'
      tags: [ 'controller.service_arguments' ]
