parameters:
  telegram:
    name:
    username:
    api:
      url:
      token:
      proxy:

framework:
  serializer:
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'

services:
  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    public: false
    tags: [ serializer.normalizer ]

  TelegramBundle\Interfaces\SendMessageInterface:
      class: TelegramBundle\SendMessageService
      public: true
      arguments:
        - '@service_container'
        - '@event_dispatcher'
        - '@serializer'

  Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter:
    tags: ['']

  TelegramBundle\Controller\ClientController:
      class: TelegramBundle\Controller\ClientController
      public: true
      arguments:
        - '@TelegramBundle\Interfaces\SendMessageInterface'
        - '@monolog.logger'
      tags: [ 'controller.service_arguments' ]
