parameters:
  telegram:
    name:
    username:
    api:
      url:
      token:
      proxy:

services:
  TelegramBundle\Interfaces\SendMessageInterface:
      class: TelegramBundle\SendMessageService
      autowire: true
      autoconfigure: true

  TelegramBundle\Controller\ClientController:
      class: TelegramBundle\Controller\ClientController
      public: true
      arguments:
        - '@TelegramBundle\Interfaces\SendMessageInterface'
        - '@logger'
      tags: [ 'controller.service_arguments' ]

  TelegramBundle\Serializer\DateTimeNormalizer:
    decorates: 'serializer.normalizer.datetime'
    autoconfigure: true
    autowire: true
